// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTOy73pEj-xXuQCHSM3KozLwLCYXoGWEE',
    appId: '1:328080399974:web:fd0baa4532d25f1bbf97a7',
    messagingSenderId: '328080399974',
    projectId: 'proje-adi-e1435',
    authDomain: 'proje-adi-e1435.firebaseapp.com',
    storageBucket: 'proje-adi-e1435.firebasestorage.app',
    measurementId: 'G-ENN1LH2LS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe19uVWWKYslTrjUAKo6fMcyDvmjiUdHQ',
    appId: '1:328080399974:android:682702cf82670c46bf97a7',
    messagingSenderId: '328080399974',
    projectId: 'proje-adi-e1435',
    storageBucket: 'proje-adi-e1435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyZtDmp0MnrJJR-FOZzn4AG58MQvLBV4',
    appId: '1:328080399974:ios:6dcb6b1a5652504fbf97a7',
    messagingSenderId: '328080399974',
    projectId: 'proje-adi-e1435',
    storageBucket: 'proje-adi-e1435.firebasestorage.app',
    iosBundleId: 'com.example.projeAdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyZtDmp0MnrJJR-FOZzn4AG58MQvLBV4',
    appId: '1:328080399974:ios:6dcb6b1a5652504fbf97a7',
    messagingSenderId: '328080399974',
    projectId: 'proje-adi-e1435',
    storageBucket: 'proje-adi-e1435.firebasestorage.app',
    iosBundleId: 'com.example.projeAdi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTOy73pEj-xXuQCHSM3KozLwLCYXoGWEE',
    appId: '1:328080399974:web:8ecae50beeb0a179bf97a7',
    messagingSenderId: '328080399974',
    projectId: 'proje-adi-e1435',
    authDomain: 'proje-adi-e1435.firebaseapp.com',
    storageBucket: 'proje-adi-e1435.firebasestorage.app',
    measurementId: 'G-PB30432LKM',
  );
}
